[build]
  command = "npm run build"
  publish = "dist/mon-soin-energetique/browser"

[[redirects]]
  from = "https://vitrinereiki.netlify.app/*"
  to = "https://mon-soin-energetique.fr/:splat"
  status = 301
  force = true