name: Unit Tests

on:
  push:
    paths:
      - 'src/**'
      - 'package.json'
  pull_request:
    branches: [ main, devop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install dependencies
        run: npm ci
      
      - name: Run unit tests
        run: ng test --watch=false --browsers=ChromeHeadless