name: Cypress Tests

on:
  push:
    paths:
      - 'src/**'      # Déclenche sur les modifications du code source
      - 'public/**'   # Déclenche sur les modifications des assets publics
      - 'package.json'
  pull_request:
    branches: [ main, master ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install dependencies
        run: npm ci
      
      - name: Run Cypress Component Tests
        uses: cypress-io/github-action@v5
        with:
          component: true